# Generated by Django 5.1.3 on 2024-12-01 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(max_length=15)),
                ('area_organizacao', models.CharField(choices=[('RH', 'Recursos Humanos'), ('TI', 'Tecnologia da Informação'), ('MK', 'Marketing'), ('ADM', 'Administração'), ('OUT', 'Outros')], max_length=50)),
                ('senha', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
